version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./mjfpl
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network: